binning:
  binsz: 0.02
  proj: 'TAN'
  coordsys: 'CEL'
  nxpix: 500
  nypix: 300
  enumbins: 10

pointing:
  ra: 245.488
  dec: -50.2708
  livetime: 50 hour

selection:
  offset_fov: 2
  emin: 0.05
  emax: 50
  ROI: 5 deg

logging:
  working_dir: .

model:
  use_psf: False
  source1: 'N877'
  spectrum1: pl
  pivot_energy1: 1
  prefactor1: 1
  index1: 2.75
  template1: Shell2D
  ra1: 245.488
  dec1: -50.2708
  rin1: 0.33
  width1: 0.2
