#!/usr/bin/env python
# Licensed under a 3-clause BSD style license - see LICENSE.rst
"""Convert ROOT files to FITS files.

TODO: explain a bit.
"""

# Parse command line arguments

from gammapy.utils.scripts import argparse, GammapyFormatter
parser = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=GammapyFormatter)
args = parser.parse_args()
args = vars(args)

# Execute script

import logging
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s - %(message)s')

# TODO: implement
raise NotImplementedError