#!/usr/bin/env python
# Licensed under a 3-clause BSD style license - see LICENSE.rst
"""Compute source model image with Astropy.

Inputs
------
* Source list (JSON file)
* PSF (JSON file)
* Exposure image (FITS file)

Outputs
-------
* Source model flux image (FITS file)
* Source model excess image (FITS file)
"""

# Parse command line arguments

from gammapy.utils.scripts import argparse, GammapyFormatter
parser = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=GammapyFormatter)
parser.add_argument('--exposure', type=str, default='exposure.fits',
                    help='Exposure FITS file name')
parser.add_argument('--psf', type=str, default='psf.json',
                    help='PSF JSON file name')
parser.add_argument('--sources', type=str, default='sources.json',
                    help='Sources JSON file name (contains start '
                    'values for fit of Gaussians)')
parser.add_argument('--model_image', type=str, default='model.fits',
                    help='Output model image FITS file name')
args = parser.parse_args()
args = vars(args)

# Execute script

import logging
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s - %(message)s')
