#!/usr/bin/env python
# Licensed under a 3-clause BSD style license - see LICENSE.rst
"""Create background model cube from off runs.

TODO: explain a bit.
"""

# Parse command line arguments

from gammapy.utils.scripts import argparse, GammapyFormatter
parser = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=GammapyFormatter)
parser.add_argument('run_list', type=str,
                    help='Input run list file name')
parser.add_argument('exclusion_list', type=str,
                    help='Input exclusion list file name')
parser.add_argument('reference_file', type=str,
                    help='Input FITS reference cube file name')
parser.add_argument('out_file', type=str,
                    help='Output FITS counts cube file name')
parser.add_argument('--clobber', action='store_true',
                    help='Clobber output files?')
args = parser.parse_args()
args = vars(args)

# Execute script

import logging
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s - %(message)s')

# TODO: implement
raise NotImplementedError