#!/usr/bin/env python
# Licensed under a 3-clause BSD style license - see LICENSE.rst
"""Perform various tasks with XSPEC files (PHA, ARF, RMF).

Depending on the subcommand used, a variety of tasks
are implemented for XSPEC files (PHA, ARF, RMF).

* info : Print summary infos
* plot : Make plots
* fake : Fake some data or IRFs.

TODO: describe
"""

# Parse command line arguments

from gammapy.utils.scripts import argparse, GammapyFormatter
parser = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=GammapyFormatter)
parser.add_argument('--clobber', action='store_true',
                    help='Clobber output files?')
args = parser.parse_args()
args = vars(args)

# Execute script

