#!/usr/bin/env python
# Licensed under a 3-clause BSD style license - see LICENSE.rst
"""Detect sources in images.

TODO: explain.
"""

# Parse command line arguments

from astropy.utils.compat import argparse
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('infile', type=str,
                    help='Input FITS file name')
args = parser.parse_args()
args = vars(args)

# Execute script

import logging
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s - %(message)s')
from gammapy import detect

raise NotImplementedError
# TODO: implement me
