#!/usr/bin/env python
# Licensed under a 3-clause BSD style license - see LICENSE.rst
"""Select a subset of runs from a given run list"""

import logging
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s - %(message)s')
from gammapy.obs import RunList

# Parse command line arguments

import sys
from astropy.utils.compat import argparse
parser = argparse.ArgumentParser(description=__doc__)
subparsers = parser.add_subparsers()

parser.add_argument('in', type=argparse.FileType('r'),
                    help='Input run list file name')
parser.add_argument('out', nargs='?', type=argparse.FileType('w'),
                    default=sys.stdout,
                    help='Output run list file name (default: stdout)')
parser.add_argument('x', type=float,
                    help='x coordinate (deg)')
parser.add_argument('y', type=float,
                    help='y coordinate (deg)')
parser.add_argument('--pix', action='store_true',
                    help='Input coordinates are pixels '
                    '(default is world coordinates)')
args = parser.parse_args()
args = vars(args)

# Execute script

print args
args['out'].write('hi\n')
print args['in'].read()
args['out'].close()
#logging.debug('Reading {0}'.format(args['infile']))
#hdus = fits.open(args['infile'])
#hdu = get_hdu(args['infile'])
#x, y = args['x'], args['y']
