#!/usr/bin/env python
# Licensed under a 3-clause BSD style license - see LICENSE.rst
"""Convert CTA IRF data from ROOT to FITS format.

Read input file from command line
irf_root_file_name = '/Users/mraue/Stuff/work/cta/2011/fits/irf/cta/SubarrayE_IFAE_50hours_20101102.root'
"""

# Parse command line arguments


from gammapy.utils.scripts import argparse, GammapyFormatter
parser = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=GammapyFormatter)
parser.add_argument('irf_root_file', type=str,
                    help='IRF ROOT file.')
parser.add_argument('-w', '--write_output', action='store_true', default=False,
                    help='Write results to FITS files in current directory.')

args = parser.parse_args()
args = vars(args)

# Execute script

import logging
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s - %(message)s')
from gammapy.utils.pyfact import cta_irf_root_to_fits

cta_irf_root_to_fits(irf_root_file_name=args['irf_root_file'],
                     write_output=args['write_output'])
