#!/usr/bin/env python
# Licensed under a 3-clause BSD style license - see LICENSE.rst
"""Run gammapy unit tests."""

# Parse command line arguments

from astropy.utils.compat import argparse
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--package', type=str, default=None,
                    help='Package to test')
args = parser.parse_args()
args = vars(args)

# Execute script

import logging
logging.basicConfig(level=logging.DEBUG, format='%(levelname)s - %(message)s')

import gammapy
gammapy.test(args['package'], verbose=True)
