name: gammapy-rtd

channels:
  - conda-forge

dependencies:
  - python=3.6
  - cython
  - numpy
  - uncertainties
  - sphinx
  - scipy
  - scikit-image
  - matplotlib
  - astropy
  - regions
  - reproject
  - aplpy
  - sphinx
