name: CI
on: [push, pull_request]

jobs:
  pre-commit:
    name: Run pre-commit hooks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false
          post-cleanup: false
      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          cache: false
          environments: pre-commit
      - name: Run pre-commit
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            pixi run pre-commit run \
            --from-ref "${{ github.event.pull_request.base.sha }}" \
            --to-ref   "${{ github.event.pull_request.head.sha }}"
          else  # push event
            pixi run pre-commit run \
            --from-ref "${{ github.event.before }}" \
            --to-ref   "${{ github.event.after }}"
          fi

  ci-runs:
    name: ${{ matrix.os }}, ${{ matrix.pixi_env }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.allowed_fail }}
    if: contains(github.event.pull_request.labels.*.name, 'skip-tests') == false
    env:
      PYTEST_ADDOPTS: --color=yes -n auto --dist=loadscope

    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            pixi_env: 'coverage'
            gammapy_data: true
            allowed_fail: false
          - os: ubuntu-latest
            pixi_env: 'py313'
            gammapy_data: true
            allowed_fail: true
          - os: ubuntu-latest
            pixi_env: 'py314'
            gammapy_data: true
            allowed_fail: true
          - os: ubuntu-latest
            pixi_env: 'all'
            gammapy_data: true
            allowed_fail: false
          # - os: ubuntu-latest
          #   pixi_env: 'oldest-deps'
          #   allowed_fail: true
          - os: macos-latest
            pixi_env: 'py313'
            gammapy_data: true
            allowed_fail: false
          - os: macos-14
            pixi_env: 'py312'
            allowed_fail: false
          - os: windows-latest
            pixi_env: 'all-no-ray'
            gammapy_data: true
            allowed_fail: false

    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false
          post-cleanup: false
      - name: Apply workarounds
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          # Workaround for https://github.com/prefix-dev/pixi/issues/3762
          sed -i.bak 's@editable = true@editable = false@g' pixi.toml
          rm pixi.toml.bak
          # Show any changes
          git diff
      - name: Apply workarounds (Windows)
        if: ${{ matrix.os == 'windows-latest' }}  # Braces are required for expressions
        shell: pwsh
        run: |
          # Workaround for https://github.com/prefix-dev/pixi/issues/3762
          (Get-Content pixi.toml) -replace 'editable = true', 'editable = false' | Set-Content pixi.toml
          git diff
      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          cache: false
          environments: ${{ matrix.pixi_env }}
      - name: Download Gammapy datasets
        if: ${{ matrix.gammapy_data }}
        run: |
          pixi run gammapy download datasets
      - name: Run tests
        if: ${{ !matrix.gammapy_data }}
        run: pixi run -e ${{ matrix.pixi_env }} pytest -- -n auto
      - name: Run tests with data
        if: ${{ matrix.gammapy_data }}
        env:
          GAMMAPY_DATA: ${{ github.workspace }}/gammapy-datasets/dev
        run: pixi run -e ${{ matrix.pixi_env }} pytest -- -n auto
      - name: Upload coverage to codecov
        if: "contains(matrix.pixi_env, 'coverage')"
        uses: codecov/codecov-action@v7
        with:
          file: ./coverage.xml
          verbose: true

      - name: Store info for sonar
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SOURCE_REPOSITORY: ${{ github.event.pull_request.head.repo.full_name }}
          SOURCE_BRANCH: ${{ github.event.pull_request.head.ref }}
          TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          pixi run pip install setuptools_scm
          # Use :- to handle unset as empty string and avoid parsing issues in SonarQube
          echo "PR_NUMBER=${PR_NUMBER}" >> sonar_env
          echo "SOURCE_REPOSITORY=${SOURCE_REPOSITORY}" >> sonar_env
          echo "SOURCE_BRANCH=${SOURCE_BRANCH:-}" >> sonar_env
          echo "TARGET_BRANCH=${TARGET_BRANCH:-}" >> sonar_env
          echo "PROJECT_VERSION=$(python -m setuptools_scm)" >> sonar_env
          cat sonar_env

      # upload coverage report for SonarQube workflow
      - uses: actions/upload-artifact@v7
        if: "contains(matrix.pixi_env, 'coverage')"
        with:
          name: gammapy-coverage-report
          path: |
            coverage.xml
            sonar_env

  sphinx:
    name: Linux python 3.12 sphinx all-deps
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      PYTEST_ADDOPTS: --color=yes -n auto --dist=loadscope
      GAMMAPY_DATA: /home/runner/work/gammapy/gammapy/gammapy-datasets/dev

    if: contains(github.event.pull_request.labels.*.name, 'skip-docs') == false

    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          run-install: false
          post-cleanup: false
      - name: Apply workarounds
        run: |
          # Workaround for https://github.com/prefix-dev/pixi/issues/3762
          sed -i.bak 's@editable = true@editable = false@g' pixi.toml
          rm pixi.toml.bak
          # Show any changes
          git diff
      - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
        with:
          cache: false
          environments: docs
      - name: download datasets
        run: |
          pixi run gammapy download datasets
      - name: test build docs
        run: |
          pixi run build-docs
      - name: Upload HTML output
        uses: actions/upload-artifact@v7
        with:
          name: gammapy-doc-html
          path: docs/_build/html/
