name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      continue-on-error: true
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Merci! We will respond to your issue shortly. In the meantime, try `import gammapy; gammapy.song()`'
        pr-message: 'Graçias! We will review your pull request shortly. In the meantime, try `import gammapy; gammapy.song(karaoke=True)`'
