name: Linkcheck

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 4'  # Every Thursday at 12:00 UTC

jobs:
  sphinx:
    name: Linux python 3.11 sphinx all-deps
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      PYTEST_ADDOPTS: --color=yes -n auto --dist=loadscope
      GAMMAPY_DATA: /home/runner/work/gammapy/gammapy/gammapy-datasets/dev
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install base dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: download datasets
        run: |
          python -m pip install tqdm requests
          python -m pip install -e .
          gammapy download datasets
      - name: check links
        continue-on-error: true
        run: |
          tox -e linkcheck -- -j auto
