name: Linkcheck

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 4'  # Every Thursday at 12:00 UTC

jobs:
  sphinx:
    name: Linux python 3.11 sphinx all-deps
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      PYTEST_ADDOPTS: --color=yes -n auto --dist=loadscope
      GAMMAPY_DATA: /home/runner/work/gammapy/gammapy/gammapy-datasets/dev
    steps:
      - name: check links
        continue-on-error: true
        run: |
          tox -e linkcheck -- -j auto
