name: Nightly wheel building

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # Every day at 05:00 UTC

jobs:
  build_wheels:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@8c8bb6c6c962542921f993d47d26df38dccd50b1 # v3.0.2
    with:
      upload_to_pypi: false
      targets: |
        - cp3*-manylinux_x86_64*
        - cp3*-macosx*
        - cp3*-win_amd64*

  notify_slack_failure:
    needs: build_wheels
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_CI_WEBHOOK }}
          SLACK_MESSAGE: 'nightly wheel build failed'
