on:
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Validate Zenodo Metadata
        uses: vsoch/zenodo-validator@main 
        with:
          path: '.zenodo.json'
