name: Create Zenodo Metadata

on:
  push:
    paths:
      - 'codemeta.json'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Convert CodeMeta to Zenodo
        uses: escape2020/codemeta2zenodo@v1.1.0
        with:
          overwrite: true

      - name: Add grants
        run: |
          cd dev && python zenodo.py

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v7.1.0
        if: success()
        with:
          commit_author: GitHub Actions <actions@github.com>
          commit_message: commit zenodo metadata file
